package me.alberto.cowrywiseconveter.mockkdata

import me.alberto.cowrywiseconveter.data.domain.model.Country

val database = arrayListOf<Country>()

fun populateDatabase(): ArrayList<Country> {
    return arrayListOf(Country(code = "AED", image = "AED"),
        Country(code = "AFN", image = "AFN"),
        Country(code = "ALL", image = "ALL"),
        Country(code = "AMD", image = "AMD"),
        Country(code = "ANG", image = "ANG"),
        Country(code = "AOA", image = "AOA"),
        Country(code = "ARS", image = "ARS"),
        Country(code = "AUD", image = "AUD"),
        Country(code = "AWG", image = "AWG"),
        Country(code = "AZN", image = "AZN"),
        Country(code = "BAM", image = "BAM"),
        Country(code = "BBD", image = "BBD"),
        Country(code = "BDT", image = "BDT"),
        Country(code = "BGN", image = "BGN"),
        Country(code = "BHD", image = "BHD"),
        Country(code = "BIF", image = "BIF"),
        Country(code = "BMD", image = "BMD"),
        Country(code = "BND", image = "BND"),
        Country(code = "BOB", image = "BOB"),
        Country(code = "BRL", image = "BRL"),
        Country(code = "BSD", image = "BSD"),
        Country(code = "BTC", image = "BTC"),
        Country(code = "BTN", image = "BTN"),
        Country(code = "BWP", image = "BWP"),
        Country(code = "BYN", image = "BYN"),
        Country(code = "BZD", image = "BZD"),
        Country(code = "CAD", image = "CAD"),
        Country(code = "CDF", image = "CDF"),
        Country(code = "CHF", image = "CHF"),
        Country(code = "CLF", image = "CLF"),
        Country(code = "CLP", image = "CLP"),
        Country(code = "CNH", image = "CNH"),
        Country(code = "CNY", image = "CNY"),
        Country(code = "COP", image = "COP"),
        Country(code = "CRC", image = "CRC"),
        Country(code = "CUC", image = "CUC"),
        Country(code = "CUP", image = "CUP"),
        Country(code = "CVE", image = "CVE"),
        Country(code = "CZK", image = "CZK"),
        Country(code = "DJF", image = "DJF"),
        Country(code = "DKK", image = "DKK"),
        Country(code = "DOP", image = "DOP"),
        Country(code = "DZD", image = "DZD"),
        Country(code = "EGP", image = "EGP"),
        Country(code = "ERN", image = "ERN"),
        Country(code = "ETB", image = "ETB"),
        Country(code = "EUR", image = "EUR"),
        Country(code = "FJD", image = "FJD"),
        Country(code = "FKP", image = "FKP"),
        Country(code = "GBP", image = "GBP"),
        Country(code = "GEL", image = "GEL"),
        Country(code = "GGP", image = "GGP"),
        Country(code = "GHS", image = "GHS"),
        Country(code = "GIP", image = "GIP"),
        Country(code = "GMD", image = "GMD"),
        Country(code = "GNF", image = "GNF"),
        Country(code = "GTQ", image = "GTQ"),
        Country(code = "GYD", image = "GYD"),
        Country(code = "HKD", image = "HKD"),
        Country(code = "HNL", image = "HNL"),
        Country(code = "HRK", image = "HRK"),
        Country(code = "HTG", image = "HTG"),
        Country(code = "HUF", image = "HUF"),
        Country(code = "IDR", image = "IDR"),
        Country(code = "ILS", image = "ILS"),
        Country(code = "IMP", image = "IMP"),
        Country(code = "INR", image = "INR"),
        Country(code = "IQD", image = "IQD"),
        Country(code = "IRR", image = "IRR"),
        Country(code = "ISK", image = "ISK"),
        Country(code = "JEP", image = "JEP"),
        Country(code = "JMD", image = "JMD"),
        Country(code = "JOD", image = "JOD"),
        Country(code = "JPY", image = "JPY"),
        Country(code = "KES", image = "KES"),
        Country(code = "KGS", image = "KGS"),
        Country(code = "KHR", image = "KHR"),
        Country(code = "KMF", image = "KMF"),
        Country(code = "KPW", image = "KPW"),
        Country(code = "KRW", image = "KRW"),
        Country(code = "KWD", image = "KWD"),
        Country(code = "KYD", image = "KYD"),
        Country(code = "KZT", image = "KZT"),
        Country(code = "LAK", image = "LAK"),
        Country(code = "LBP", image = "LBP"),
        Country(code = "LKR", image = "LKR"),
        Country(code = "LRD", image = "LRD"),
        Country(code = "LSL", image = "LSL"),
        Country(code = "LYD", image = "LYD"),
        Country(code = "MAD", image = "MAD"),
        Country(code = "MDL", image = "MDL"),
        Country(code = "MGA", image = "MGA"),
        Country(code = "MKD", image = "MKD"),
        Country(code = "MMK", image = "MMK"),
        )
}